<?php

namespace app\admin\controller;

use app\common\model\Category;
use think\Controller;

class Audio extends Controller
{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Audio();
    }

    //首页
    public function index()
    {
        $field = $this->db->getAll(2);
        $this->assign('field',$field);
        return $this->fetch();
    }
    //添加
    public function store()
    {
        if (request()->isPost())
        {
            $res = $this->db->store(input('post.'));
            if ($res['valid'])
            {
                $this->success($res['msg'],'index');exit;
            }else{
                $this->error($res['msg']);exit;
            }
        }
        //1.获取分类数据
        $cateData = (new Category())->getAll();
        //halt($cateData);
        $this->assign('cateData',$cateData);
        //2。获取标签数据
        $tagData = db('tag')->select();
        //halt($tagData);
        $this->assign('tagData',$tagData);
        return $this->fetch();
    }
    //音频编辑
    public function edit()
    {

        if (request()->isPost())
        {
            $res = $this->db->edit(input('post.'));
            if ($res['valid'])
            {
                $this->success($res['msg'],'index');exit;
            }else{
                $this->error($res['msg']);exit;
            }
        }

        //获取音频audio_id
        $video_id = input('param.audio_id');
        //获取音频数据
        $audioData = $this->db->find($video_id);
        //halt($videoData);exit;
        $this->assign('audioData',$audioData);

        //1.获取分类数据
        $cateData = (new Category())->getAll();
        //halt($cateData);
        $this->assign('cateData',$cateData);
        //2。获取标签数据
        $tagData = db('tag')->select();
        //halt($tagData);
        $this->assign('tagData',$tagData);

        //3.获取文章标签数据
        $arcTag = db('arc_tag')->select();
        //halt($arc_tag[0]);
        $this->assign('arcTag',$arcTag);

        return $this->fetch();
    }

    //回收站
    public function recycle()
    {
        //echo 1;exit;
        $field = $this->db->getAll(1);
        $this->assign('field',$field);
        return $this->fetch();
    }
    //删除回收站
    public function del()
    {

        $res = $this->db->del(input('get.audio_id'));
        if ($res['valid'])
        {
            $this->success($res['msg'],'recycle');exit;
        }else{
            $this->error($res['msg']);exit;
        }

    }
    //从回收站移回列表
    public function getRecycle()
    {
        $res = $this->db->getRecycle(input('get.audio_id'));
        if ($res['valid'])
        {
            $this->success($res['msg'],'index');exit;
        }else{
            $this->error($res['msg']);exit;
        }
    }
}
