<?php

namespace app\web\controller;
use think\Controller;

class Article extends Controller
{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Article();
    }
    //文章详情
    public function detail()
    {
        $field = $this->db->apiGetArcDetail(request()->param('article_id'));
        $this->assign('field',$field);
        return $this->fetch();
    }
}
